# Generated by Django 3.2.20 on 2023-07-03 08:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('requests', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('moving_up', 'Moving Up'), ('moving_down', 'Moving Down'), ('door_open', 'Door Open'), ('stopped', 'Stopped')], default='Idle', max_length=20)),
                ('is_running', models.BooleanField(default=True)),
                ('is_door_open', models.BooleanField(default=False)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.system')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
