# Generated by Django 3.2.20 on 2023-07-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20230703_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.system'),
        ),
    ]
